### ISSUE TITLE
Kinetics 400 Exploration

### ISSUE THREAD

**Issue by gabeorlanski** [gabeorlanski/adversarial-robustness-toolbox#1]
- [x]  File formats
- [x]  Simple Examples
- [x]  Complex Examples
- [x]  Data Types
- [x]  (?) Memory Issue
- [x]  Provided Preprocessing
- [x]  ART Preprocessing

[Kinetics 400 Dataset](https://deepmind.com/research/open-source/kinetics)

**Comment by seanhung07** [comment]
**File formats**

- Three csv files and three json files:  test.csv, train csv, and validate.csv (all the video comes from youtube). There is a youtube_id category that we can get all the video

**Comment by kwockn17** [comment]
Not sure if this is exactly provided preprocessing, but here's the first search result for "kinetics 400 preprocessing." 

Thread:
https://github.com/deepmind/kinetics-i3d/issues/34

Comment in thread:
https://github.com/deepmind/kinetics-i3d/issues/34#issuecomment-534409800

Link to mediapipe tool for preprocessing:
https://github.com/google/mediapipe/tree/master/mediapipe/examples/desktop/media_sequence

**Comment by seanhung07** [comment]
| label | youtube_id | time_start | time_end | split | example link |
| -- | -- | -- | -- | -- | -- |
| drinking beer | --6bJUbfpnQ | 17 | 27 | test | https://youtu.be/--6bJUbfpnQ?t=17 |
