### ISSUE TITLE
I3D Exploration

### ISSUE THREAD

**Issue by gabeorlanski** [gabeorlanski/adversarial-robustness-toolbox#2]
- [x] Get it to run
- [x] See what their preprocessing is and if it is open source & summarize 
- [x] Run Evaluation and get baseline results
- [x] See if we can make a confusion matrix

[I3D git](https://github.com/deepmind/kinetics-i3d)

**Comment by gabeorlanski** [comment]
This is the working link to the google preprocessing pipeline https://github.com/google/mediapipe

**Comment by jfang2799** [comment]
No preprocessing:
"Args:
      inputs: Inputs to the model, which should have dimensions
          `batch_size` x `num_frames` x 224 x 224 x `num_channels`."

**Comment by gabeorlanski** [comment]
> No preprocessing:
> "Args:
> inputs: Inputs to the model, which should have dimensions
> `batch_size` x `num_frames` x 224 x 224 x `num_channels`."

there is, it uses the google media pipe as the preprocessing.

**Comment by gabeorlanski** [comment]
I3D is dependent on python 3.6 libraries and older cuda versions. So we may need to look at other models.

**Comment by gabeorlanski** [comment]
We should consider https://github.com/open-mmlab/mmaction2. There is a google colab notebook that runs on the kinetic 400, and does well.
